### ISSUE TITLE
[BUG] configure cannot found toolchain

### ISSUE THREAD

**Issue by Myushu** [aldebaran/qibuild#101]
Hi,

I have a big issue  with the last version (3.12rc4) : I cannot configure my projet. Cmake cannot find the dependencies stored on my toolchain.

I don't have any problem with the homebrew version 3.11.6.

**Comment by alkino** [comment]
Hi,
Can you paste us the output of your configuration with "--verbose"?

Thanks,

nicolas

**Comment by Myushu** [comment]
Hi,

Sorry, it's my bad. I forgot to check the change log.
After update my `project.xml` it's working well.

Thanks,
