### ISSUE TITLE
Toolchain package version number is not used to name the .zip result

### ISSUE THREAD

**Issue by victorpaleologue** [aldebaran/qibuild#121]
## Protocol
Take a C++ qibuild project.
Add a package.xml like this:
```
<package name="bar" target="linux64" version="1.2.3">
<license>BSD</license>
  <depends buildtime="true" runtime="true" names="foo" />
</package>
```
Call `qibuild package` on the project.

## Expected
It produces bar-1.2.3-<config_name>.zip

## Observed
It produces bar-**0.1**-<config_name>.zip

**Comment by vbarbaresi** [comment]
If I recall correctly, package.xml is produced by `qibuild package`, not a part of the sources.
The version comes from qiproject.xml file (or from `--version` argument)

**Comment by victorpaleologue** [comment]
Alriiiight, that's much more clearer now.
Thanks.
