### ISSUE TITLE
Can't save project inside Pepper robot

### ISSUE THREAD

**Issue by soumenms2015** [aldebaran/qibuild#124]
Hello,
I am currently working with Pepper robot and my project is not being saved inside the Pepper. EVerytime, I have to connect Pepper with laptop in order to make it work. I am currently using Choregraphe 2.8.2.15 version for creating my project. The moment I upload the project inside robot and it showing some warning message " Choregraphe-2.8.2.15 my not be compatible with NAOqi-2.5.3. Choregraphe and your behaviours may work strangely. it is highly recommended to update NAOqi and / or Choregraphe.
Thank you very much for any help:)
Regards,
Soumen

**Comment by victorpaleologue** [comment]
This GitHub project is for the build system provided along with NAOqi and libQi.
I think your issue is rather a general purpose one, and should rather be solved by StackOverflow's community: https://stackoverflow.com/questions/tagged/pepper?mixed=1
Please try there instead.
