### ISSUE TITLE
qibuild package runtime problem

### ISSUE THREAD

**Issue by Fantomatic** [aldebaran/qibuild#24]
I've got an issue with a fonctionnality in the documentation. It's the qibuild package who is supposed to have an option --runtime to package the project AND the dependencies resolved by the qiproject.xml.
Infortunatly, i don't saw any option of this kind in the qibuild package --help. 
Is this fonctionnality still present but elsewhere ? is this a bug of the last release (i'm on the 3.8.2) ? 
Or is the fonctionnality abandoned and the documentation not update ?

**Comment by dmerejkowsky** [comment]
Yeah, the doc about qibuild package is out of date. (Sorry about that).
qibuild package should only be used to generate packages for qitoolchain.

If you want to provide pre-compiled binaries, use qibuild install --runtime /path/to/dest, and make 
a zip from the install dir
