### ISSUE TITLE
qisrc and tags

### ISSUE THREAD

**Issue by Fantomatic** [aldebaran/qibuild#25]
I've got an issue with the use of qisrc. I saw your implentation of branches in the manifest, but where are tags ? technically it's almost the same thing and i don't understand why it isn't present. When we talk about version of a project in git, isn't it normal to use tags ?

**Comment by Grimy** [comment]
As a workaround, you can name your remote `refs/tags`. This will make it work correctly for tags, but will break branches. I’m working on a PR to make both work fine.

**Comment by vbarbaresi** [comment]
What is your use case? The purpose of the branch in the manifest is to configure a tracking branch on your repositories.
If you just want to reset on a given tag, use the qisrc reset feature with a snapshot. It will fetch and reset on tags or SHA1s.

**Comment by Grimy** [comment]
@vbarbaresi I want to get a specific version of a great number of repositories (for example, v4.6.5.0 of repo A, v1.9.3 of repo B…). Furthermore, I want the file specifying the list of repositories and their versions to be in source control. Unless I’m mistaken `qisrc reset` doesn’t allow that. Plus, there’s really no reason for qisrc to not handle tag (it’s really trivial to implement, see my PR).

**Comment by vbarbaresi** [comment]
You're free to put a ``snapshot.txt`` file under version control.
A JSON file containing refs like this:
> "refs": {
>  "tools/qibuild": "v3.8",
>  "lib/mylib": "v1.2"
> }

Then ``qisrc reset --snapshot snapshot.txt`` would do the trick.

Your patch will work, but it clashes with the semantic of the branch parameter. You can't  *track* a tag. There are commands like ``qisrc status`` that rely on this tracking semantic.

**Comment by Grimy** [comment]
Thanks for your answer; I didn’t know about `qisrc reset --snapshot`. I will investigate it further.

Is there any documentation about this feature, and in particular about the syntax of the `snapshot.txt` file? `grep -R snapshot doc` finds no results outside of the changelog, and `qisrc reset --help` is unhelphul.

**Comment by dmerejkowsky** [comment]
Sadly there's no documentation about the snapshot file format. I'll fix that later.
It's a JSON file looking like:

```json
{
  "format" : "2",
  "refs" : {
     "foo" : "v3.8",
      ...
  },
  "manifest" : {
           "url" : "<manifest url>",
           "groups" : [
                 "<list of groups>"
           ],
          "branch" : "<manifest branch>"
  }
```

You may wondering why you have to have info about the manifest in the snapshot. That's because
the path of the repositories given in the `refs` dict are allowed to change in the manifest, so we first need to reset the manifest to where it was when the snapshot was generated.

Note that you can use `qisrc snapshot` to generate a snapshot from your worktree that you can edit later

**Comment by Fantomatic** [comment]
super pour l'update. Vous pensez mettre la 3.12 dans combien de temps environ sur le master ? 1 mois ? 3 mois ? ou c'est pas du tout defini ?

**Comment by dmerejkowsky** [comment]
Not sure. We have to release 3.11 first.  I'll say in about a month. We have other stuff planned for 3.12

**Comment by Fantomatic** [comment]
okai, perfect. Just one more question : i tried to do the pulling with qisrc init for tags and i wasn't able to do it. 
i use this manifest to test it :
<manifest>
  <remote name="origin" url="git@10.12.145.249" />
  <project name="foor/bar" remotes='origin' ref="v5.0.0.0RC1" src="Core" />                        
</manifest>
and i don't have any fail, but no pulling either.

**Comment by Fantomatic** [comment]
Would you mind telling me how to make tags work in the manifest ? i used this one as a test :
```xml
<manifest>                                                                                               
    <remote name="origin" url="git@10.33.162.249" />
    <project name="EDF/Core64" remotes='origin' ref="v5.0.0.0RC1" src="Core" />
</manifest>```
No failure but it doestn't pull anything

**Comment by dmerejkowsky** [comment]
can your run `qisrc init` with the --verbose flag and post the complete output of the command ?

**Comment by dmerejkowsky** [comment]
Found it

```
<project name="foo.git"
```

was the syntax in qisrc2

in qisrc 3 it was changed to

```
<repo project="foo.git"
```

(My comment on #46 was misleading, sorry about that)

**Comment by Fantomatic** [comment]
okai that was that indeed
