### ISSUE TITLE
qitoolchains default

### ISSUE THREAD

**Issue by Fantomatic** [aldebaran/qibuild#29]
The command "qitoolchain create <TOOLCHAIN_NAME>" can take an argument --default according to your documentation. I guess it has to be not up to date anymore, but i don't understand why it isn't in qibuild ?  Is there a specific reason ? Are you manually adding the toolchain to the project if you don't want to use the option -c <TOOLCHAIN_NAME> when you build ?

**Comment by dmerejkowsky** [comment]
When you have created a build config with `qibuild add-config <name> -t <toolchain name>`, you can use `qibuild set-default <name>`. The documentation sure needs to be updated

**Comment by Fantomatic** [comment]
perfect thank you !
