### ISSUE TITLE
macro CMake toolchain

### ISSUE THREAD

**Issue by Fantomatic** [aldebaran/qibuild#31]
I wanted to know if there was a possibility to put a macro cmake in a toolchain ?
It could be a nice way to delete all the CmakeModules of my project.

**Comment by dmerejkowsky** [comment]
I'm not sure I understand your question. Usually the cmake modules are finders to third-party libraries, and those belong inside the packages of the toolchains. The one you see in qibuild/cmake/qibuild/modules are for you are not using any toolchain and want to find the libs on your system.

**Comment by Fantomatic** [comment]
yes but you can instead make them the executable instead. you can call them usually with an include in the CMakeLists and then just using in it as a function. 
Exemple : aFile.cmake has a macro calcul() in it. 
In the CMakeLists : 
include(aFile)
calcul()

The main problem is my lack of knowledge about how qibuild set the CMake_Module_Path, and how can we add something in it without destroying the automatic task he mad.

**Comment by dmerejkowsky** [comment]
You can use:

```cmake
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}")
```

Or you can use qi_stage_cmake so that aFile.cmake can be found even from an other project:

http://doc.aldebaran.com/qibuild/advanced/cmake/api/stage.html#qi_stage_cmake

**Comment by Fantomatic** [comment]
thanks a lot !
