### ISSUE TITLE
qitest --coverage

### ISSUE THREAD

**Issue by Fantomatic** [aldebaran/qibuild#39]
Hi, 
I encounter a problem with the command qitest when i'm using it on my CMake project working with qibuild.
The tests are working great but i need coverage. The verbose option when i'm typing the command qitest --coverage -c [TOOLCHAIN] [PROJECT_NAME] allow me to see this :
> [DEBUG]:  [qitest.actions.run] arguments:
> action            = run
> all               = False
> backtrace         = False
> break_on_failure  = False
> build_prefix      = None
> color             = auto
> config            = linuxTest
> coverage          = True
> dep_types         = default
> groups            = None
> home              = None
> nightly           = False
> nightmare         = False
> num_cpus          = -1
> num_jobs          = 1
> patterns          = None
> pdb               = False
> perf              = False
> projects          = ['Core']
> qitest_jsons      = None
> quiet             = False
> repeat_until_fail = 0
> root_output_dir   = None
> single            = False
> timestamp         = False
> title             = auto
> use_deps          = False
> valgrind          = False
> verbose           = True
> verbose_tests     = False
> worktree          = None
> [ERROR]:  Exception --coverage can only be used from a qibuild CMake project

I have used qibuild configure with the option --coverage too, and build my project without any trouble.
Is this a bug or did i made a mistake ?

**Comment by d0nn13** [comment]
It is a bug fixed recently and it should be included in the next release.
