### ISSUE TITLE
generation of .cmake trouble

### ISSUE THREAD

**Issue by Fantomatic** [aldebaran/qibuild#48]
Hi, 
We've got a quiet big trouble with qibuild when it comes to make a package with a more recent version of qibuild than 3.9.2. 
With both the ways "qibuild package" or "qitoolchain make-package", it comes to a point where the generation of the .cmake in the share are wrong and doesn't work. 

We were creating a sdk of a project with multiple libraries and binaries. We wanted to put it in the toolchain but we saw that the path where cmake wanted to search for a library or a binary, wasn't correct. 
In fact, since 3.10, you made a major change in the way the .cmake are generated and it seem that it doesn't handle well the concept of suffixe in path.

Ultimatly, we can saw it in any .cmake in the share directory, that the path lack a "/"  in it to be correct. 
In the 3.9.2, it worked with the ancient ( and less understandable we have to admit ) version of these .cmake. Might have something to do with the suffixe handle in the cmake 3.9.2.

I post with that 2 screenshot of the same library with both the version : 

Version with qibuild 3.9
![lib3 9](https://cloud.githubusercontent.com/assets/6103180/12443708/2dd9d7a2-bf5a-11e5-9190-ae8ce2a27f08.png)

Version with qibuild 3.11
![lib3 11](https://cloud.githubusercontent.com/assets/6103180/12443709/2e021d8e-bf5a-11e5-8173-3665730f7243.png)

In this exemple, the wrong path is the UTILITAIRE_LIBRARIES and we can see that there is a lack of a '/' between 'lib' and 'igc'.

**Comment by dmerejkowsky** [comment]
This indeed is a bug but I have to warn you.

Having a staged library in a custom suffix, like ``lib/igc/libUtilitaire.so`` is likely to cause problems at runtime.

Let's say you have a ``foo`` binay that does ``qi_use_lib(foo utilitaire)``

When you install ``foo`` you will end up with ``foo``in ``bin/foo`` and ``libUtilitaire.so`` in ``lib/igc``, 
but the ``RPATH`` set by ``qi_create_bin`` will be ``$origin/../lib``, so the operating system will not manage to find the ``libUtilitaire.so`` library when running ``foo``.

Usually libraries in a prefix are ``modules`` in CMake terminology, or ``plugins`` if you prefer, that are used with ``dlopen`` at runtime.

If you really want your library in a prefix, you can still do something like

```cmake

# Prevent qi_create_bin to set install rpath:
qi_create_bin(foo foo.pp NO_RPATH)
qi_use_lib(foo UTILITAIRE)
set_target_properties(foo 
   PROPERTIES
     INSTALL_RPATH "\$ORIGIN/../lib/igc")
```

**Comment by Fantomatic** [comment]
Yes, we already use this property in our library.
We have have these declared earlier in the project : 
```cmake
set(CORE_BIN_RPATH
  "\$ORIGIN/../../lib/igc"
  CACHE INTERNAL "" FORCE
)
set(CORE_PUBLIC_BIN_RPATH
  "\$ORIGIN/../lib/igc"
  CACHE INTERNAL "" FORCE
)
set(CORE_LIB_RPATH
  "\$ORIGIN"
  CACHE INTERNAL "" FORCE
)
set(CORE_PLUGIN_RPATH
  "\$ORIGIN/../.."
  CACHE INTERNAL "" FORCE
)
```

and then 
```cmake
set_target_properties(foo 
   PROPERTIES
     INSTALL_RPATH "\$ORIGIN/../lib/igc"
```

**Comment by dmerejkowsky** [comment]
I've made a pull request to fix the bug. Tell me if it fixes your problem

**Comment by Fantomatic** [comment]
I have tested it and it worked ! 
![lib3 12](https://cloud.githubusercontent.com/assets/6103180/12450994/0fd89b1c-bf87-11e5-97f2-9acdcd04c466.png)

Sadly i saw another change that i don't understand (maybe just because it's an unfinished version). 
When i wanted to configure my project with my toolchain, cmake couldn't find my packages. I just set packages path with PACKAGE_DIR for this time, but i guess there is a change i didn't saw ?

**Comment by dmerejkowsky** [comment]
Please open an other issue. This one is closed
