### ISSUE TITLE
Rewrite qisys.archive using arclib ?

### ISSUE THREAD

**Issue by dmerejkowsky** [aldebaran/qibuild#79]
See here: https://arclib.readthedocs.org/en/latest/

There's little value in re-inventing the wheel here.

Also, if arclib does not contain all the features we need (such as progress bars, handling symlinks in zips and so on ...), it may be worth contributing upstream

**Comment by vbarbaresi** [comment]
The project started 2 days ago, there are 0 releases. Very few tests.
I don't see why we would replace our 4 year old tested implementation with what seems like a random project on GitHub

**Comment by dmerejkowsky** [comment]
Hum, maybe you're right :P 

Closing
