### ISSUE TITLE
qipkg insert end of lines depending on the OS

### ISSUE THREAD

**Issue by fbriand** [aldebaran/qibuild#88]
I launched qipkg make-package for my package from my computer (Windows10) and deployed on the robot but when I try to execute the python file at the package root, an error occurs because the file contains Windows end of lines:
`-bash: ./python: /bin/bash^M: bad interpreter: No such file or directory`

**Comment by vbarbaresi** [comment]
Hey, I was going to fix that!
I'm pretty sure it's the right fix

**Comment by fbriand** [comment]
Tested, it fixes it, thx Dimitri! (and hello Vincent)
Shall I close this issue or should we wait for it to be merged before closing?

**Comment by vbarbaresi** [comment]
I'll close it tomorrow after I merge the fix
Thanks everyone
